name: startwith-batch CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # YML 파일 생성
      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Set YML TEST
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_TEST_YML }}" | base64 --decode > src/main/resources/application-test.yml

      # Gradle Build
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      # Docker Config
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USERNAME}}
          REPO: startwith-batch
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set Docker permissions
        run: |
          sudo usermod -aG docker $USER
          sudo chown $USER /var/run/docker.sock
          newgrp docker

      - name: Clean up Docker to free space
        run: |
          sudo docker container prune -f
          sudo docker image prune -a -f
          sudo docker volume prune -f
          sudo docker network prune -f
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean
          sudo apt-get autoremove

      - name: Run Docker
        run: |
          sudo docker ps -q --filter "name=startwith-batch" | grep -q . && sudo docker stop "startwith-batch" && sudo docker rmi -f "${{secrets.DOCKER_USERNAME}}/startwith-batch"
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/startwith-batch
          sudo docker run -d --name startwith-batch --rm -p 8080:8080 ${{secrets.DOCKER_USERNAME}}/startwith-batch